Rigid Body Dynamics Library: src/Model.cc File Reference
Model.cc File Reference
Functions
unsigned int AddBodyFixedJoint (Model &model, const unsigned int parent_id, const SpatialTransform &joint_frame, const Joint &joint, const Body &body, std::string body_name)
unsigned int AddBodyMultiDofJoint (Model &model, const unsigned int parent_id, const SpatialTransform &joint_frame, const Joint &joint, const Body &body, std::string body_name)
Function Documentation
unsigned int AddBodyFixedJoint (Model & model, const unsigned int parent_id, const SpatialTransform & joint_frame, const Joint & joint, const Body & body, std::string body_name)
Definition at line 89 of file Model.cc.
References FixedBody::CreateFromBody(), SpatialRigidBodyInertia::createFromMassComInertiaC(), Model::fixed_body_discriminator, Model::I, Model::IsFixedBodyId(), Body::Join(), Model::mBodies, Model::mBodyNameMap, Body::mCenterOfMass, Model::mFixedBodies, Body::mInertia, Body::mMass, FixedBody::mMovableParent, and FixedBody::mParentTransform.
unsigned int AddBodyMultiDofJoint (Model & model, const unsigned int parent_id, const SpatialTransform & joint_frame, const Joint & joint, const Body & body, std::string body_name)
Definition at line 148 of file Model.cc.
References Model::AddBody(), RigidBodyDynamics::JointType1DoF, RigidBodyDynamics::JointType2DoF, RigidBodyDynamics::JointType3DoF, RigidBodyDynamics::JointType4DoF, RigidBodyDynamics::JointType5DoF, RigidBodyDynamics::JointType6DoF, RigidBodyDynamics::JointTypeFloatingBase, RigidBodyDynamics::JointTypePrismatic, RigidBodyDynamics::JointTypeRevolute, RigidBodyDynamics::JointTypeSpherical, RigidBodyDynamics::JointTypeTranslationXYZ, Body::mIsVirtual, Joint::mJointAxes, and Joint::mJointType.